#! /usr/bin/env node

'use strict';

const program = require('commander');

const cliVersion = require('../../package.json').version;

program
  .version(cliVersion, '-v, --version');

program
  .command('build', 'Build a static site');

program
  .command('content', 'Commands related to the main site content');

program
  .command('styleguide', 'Commands related to the styleguide content');

program
  .parse(process.argv);
